[package]
name = "hn00"
version = "0.1.0"
authors = ["Michael Angerman <stormasm@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "*"
redis = "*"
reqwest = "0.10.0-alpha.1"
hyper-tls = "0.4.0-alpha.4"
tokio = "0.2.0-alpha.5"
hyper = "0.13.0-alpha.4"
